config/urls.py
"""
LineGest URL Configuration
"""

from django.contrib import admin
from django.urls import path, include
from django.views import defaults as default_views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("linegest.pages.urls")),
    path("users/", include("linegest.users.urls")),
]

if settings.DEBUG:
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    urlpatterns += (
        staticfiles_urlpatterns()
    )  # tell gunicorn where static files are in dev mode
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=str(settings.MEDIA_ROOT),
    )

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [
            path("__debug__/", include(debug_toolbar.urls))
        ] + urlpatterns

linegest/pages/urls.py
from django.urls import path
from .views import home_view

app_name = "pages"

urlpatterns = [
    path("", home_view, name="home"),
]

linegest/users/urls.py
from django.urls import path, include

app_name = "users"

urlpatterns = [
    path("", include("django.contrib.auth.urls")),
]

linegest/pages/models.py
from django.db import models

# Create your models here.

linegest/phoneline/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from datetime import datetime


class Period(models.Model):
    class Month(models.IntegerChoices):
        JANVIER = 1, _("Janvier")
        FEVRIER = 2, _("Février")
        MARS = 3, _('Mars')
        AVRIL = 4, _("Avril")
        MAI = 5, _("Mai")
        JUIN = 6, _("Juin")
        JUILLET = 7, _("Juillet")
        AOUT = 8, _("Août")
        SEPTEMBRE = 9, _("Septembre")
        OCTOBRE = 10, _("Octobre")
        NOVEMBRE = 11, _("Novembre")
        DECEMBRE = 12, _("Décembre")

        def __str__(self):
            return f"{self.name}"

    year = models.IntegerField()
    month = models.IntegerField('Month', choices=Month)
    period_date = models.DateField(blank=True, null=True)

    def __str__(self):
        return f"{self.get_month_display()}-{self.year}"

    @classmethod
    def get_id_period(cls, year, month):
        periods = cls.objects.filter(year=year, month=month)
        if periods:
            return periods[0].id

    @property
    def get_period_date(self):
        return datetime.strptime(f'{self.year}-{self.month}-01', '%Y-%m-%d').date()


    @classmethod
    def get_list_month(cls):
        return [month.value for month in cls.Month]

    @classmethod
    def get_missing_month(cls, year):
        periods = cls.objects.filter(year=year)
        missing_months = [num_month for num_month in [x for x in range(1,13)] if num_month not in [period.month for period in periods]]
        return missing_months

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['year', 'month'], name='unique_period')
        ]

    def save(self, *args, **kwargs):
        if not self.period_date:
            self.period_date = self.get_period_date

        super().save(*args, **kwargs)


class Category(models.Model):
    name = models.CharField(max_length=50)
    tag = models.CharField(max_length=20)

    @classmethod
    def get_default_pk(cls):
        category, created = cls.objects.get_or_create(
            tag='NOT_DEF',
            defaults=dict(name='Not define'),
        )
        return category.pk

    def __str__(self):
        return self.name


class StatusTaxatLine(models.Model):
    name = models.CharField(max_length=10, unique=True)

    class Meta:
        verbose_name = "Status de taxation"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Label(models.Model):
    label_id = models.IntegerField()
    display_name = models.CharField(max_length=255, verbose_name='Nom du Label')
    description = models.TextField(blank=True, verbose_name='Description')
    category = models.ForeignKey("Category",
                                   related_name='labels',
                                   on_delete=models.SET_DEFAULT,
                                   verbose_name="Category",
                                   default=Category.get_default_pk
                                   )

    def __str__(self):
        return self.display_name


class LinePhone(models.Model):
    phone_number = models.CharField(max_length=10)
    period = models.ForeignKey("Period", on_delete=models.CASCADE, related_name='line_phones')
    label = models.ManyToManyField("Label", blank=True, related_name='line_phones')
    status_taxa_line = models.ForeignKey("StatusTaxatLine", on_delete=models.CASCADE, related_name='line_phones')

linegest/users/models.py
from django.db import models
from django.contrib.auth import models as auth_models


class User(auth_models.AbstractUser):
    """Utilisateur personnalisé pour l'application."""

linegest/pages/views.py
from django.views.generic import TemplateView


class HomeView(TemplateView):
    template_name = "pages/home.html"


home_view = HomeView.as_view()

linegest/phoneline/views.py
from django.shortcuts import render

# Create your views here.

linegest/templates/base.html
{% load webpack_loader static %}

<!doctype html>
<html lang="fr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <title>{% block title %}{% endblock title %}</title>
    
    {% block head_styles %}
      {% stylesheet_pack 'app' %}
    {% endblock head_styles %} 
    
    {% block head_scripts %}
      {% javascript_pack 'app' attrs='defer' %}
    {% endblock head_scripts %}
  </head>
  <body class="{% block body_classes %}position-relative min-vh-100{% endblock body_classes %}">
    {% block messages %}{% include 'partials/messages.html' %}{% endblock messages %}
    
    {% block navigation %}{% include 'partials/navigation.html' %}{% endblock navigation %}
    
    {% block header %}{# placer l'en-tête de la page ici #}{% endblock header %}
    
    {% block outer_content %}
        <main class="flex-grow-1 container">
          {% block content %}{# placer le contenu principal ici #}{% endblock content %}
        </main>
    {% endblock outer_content %}
    
    {% block footer %}{% include 'partials/footer.html' %}{% endblock footer %}
    
    {% block modal %}{# placer vos fenêtres modales ici #}{% endblock modal %}
    
    {% block bottom_scripts %}{# placer vos scripts de bas de page ici #}{% endblock bottom_scripts %}
  </body>
</html>

linegest/templates/pages/home.html
{% extends 'base.html' %}

{% block title %}Home | LineGest{% endblock title %}

{% block content %}
    <div class="container">
        <h1>Welcome to project LineGest</h1>
    </div>
{% endblock content %}«

linegest/templates/partials/footer.html
<footer class="position-absolute bottom-0 w-100 bg-dark text-light p-3">
    <div class="container">
        &copy; 2023 Mickaël
    </div>
</footer>

linegest/templates/partials/messages.html
<div class="container">
  {% if messages %}
    {% for message in messages %}
    <div class="alert alert-dismissible {% if message.tags %}{{ message.tags }}{% endif %}">
      {{ message }}
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
  {% endif %}
</div>

linegest/templates/partials/navigation.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="#">LineGest</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                {% url 'pages:home' as url %}
                <li class="nav-item">
                <a class="nav-link {% if request.path == url %}active{% endif %}" {% if request.path == url %}aria-current="page"{% endif %} href="{{ url }}">Home{% if request.path == url %} <span class="visually-hidden">(current)</span>{% endif %}</a>
                </li>
                {% url 'admin:index' as url %}
                <li class="nav-item">
                <a class="nav-link" href="{{ url }}" target="_blank">Admin</a>
                </li>
                {% if not user.is_authenticated %}
                {% url 'users:login' as url %}
                <li class="nav-item">
                    <a class="nav-link {% if request.path == url %}active{% endif %}" {% if request.path == url %}aria-current="page"{% endif %} href="{{ url }}">Login {% if request.path == url %} <span class="visually-hidden">(current)</span>{% endif %}</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>